import gspread
from oauth2client.service_account import ServiceAccountCredentials

class GSheetUtil:
    def __init__(self):
        #connect and open the google sheet
        scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
        #credentials json file generated by googleAPI
        creds = ServiceAccountCredentials.from_json_keyfile_name('config/client_secret.json', scope)
        #open google sheet
        self.sheet = gspread.authorize(creds).open('Plan of Investment')
        print('######## google sheet opened ########')
        #worksheet = self.sheet.worksheet("Dashboard")
        #aux = worksheet.acell('H6').value
        #print(aux)

    def getSheet(self):
        return self.sheet
