#!/usr/local/bin/python
# -*- coding: utf-8 -*-
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from constants import (GOOGLE_SHEETS_HOME, GOOGLE_DRIVE_AUTH)
class GSheetUtil:

    def __init__(self):
        #connect and open the google sheet
        scope = [GOOGLE_SHEETS_HOME, GOOGLE_DRIVE_AUTH]
        #credentials json file generated by googleAPI
        creds = ServiceAccountCredentials.from_json_keyfile_name('config/client_secret.json', scope)
        #open google sheet
        self.sheet = gspread.authorize(creds).open('Plan of Investment')
        print('######## google sheet opened ########')

    def getSheet(self):
        return self.sheet
